{% set version = "1.8-14" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-hiddenmarkov
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/HiddenMarkov_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/HiddenMarkov/HiddenMarkov_{{ version }}.tar.gz
  sha256: 250b22c19e358eb9b602dc07b894ad30ca18c2670dd80afccb9ccd7d23cf6025

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ stdlib("c") }}                # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ stdlib("m2w64_c") }}          # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('HiddenMarkov')"           # [not win]
    - "\"%R%\" -e \"library('HiddenMarkov')\""  # [win]

about:
  home: http://www.statsresearch.co.nz/dsh/sslib/
  license: GPL-2.0-or-later
  summary: Contains functions for the analysis of Discrete Time Hidden Markov Models, Markov Modulated GLMs and the Markov Modulated Poisson Process. It includes functions for simulation, parameter estimation, and the Viterbi algorithm. See the topic "HiddenMarkov" for an introduction to the package, and "Change Log" for
    a list of recent changes. The algorithms are based of those of Walter Zucchini.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - sebastian-luna-valero
