{% set version = '1.8-11' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-hiddenmarkov
  version: {{ version|replace("-", "_") }}

source:
  fn: HiddenMarkov_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/HiddenMarkov_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/HiddenMarkov/HiddenMarkov_{{ version }}.tar.gz
  sha256: 4a1614249eee9f428bc182ea9ced443dff4eafa7babf4259c720e5b4da2d08fa

build:
  merge_build_host: True  # [win]
  number: 1002
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('fortran') }}  # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('m2w64_fortran') }}        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
  run:
    - r-base
    - {{native}}gcc-libs         # [win]

test:
  commands:
    - $R -e "library('HiddenMarkov')"           # [not win]
    - "\"%R%\" -e \"library('HiddenMarkov')\""  # [win]

about:
  home: http://www.statsresearch.co.nz/dsh/sslib/
  license: GPL (>= 2)
  summary: Contains functions for the analysis of Discrete Time Hidden Markov Models, Markov
    Modulated GLMs and the Markov Modulated Poisson Process. It includes functions for
    simulation, parameter estimation, and the Viterbi algorithm. See the topic "HiddenMarkov"
    for an introduction to the package, and "Change Log" for a list of recent changes.
    The algorithms are based of those of Walter Zucchini.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - conda-forge/r
    - sebastian-luna-valero
