travis:
  secure:
    BINSTAR_TOKEN: C821SGMeYSwvLHexxNOnofJr3ta827X5yFAz8u4rxXxItO1SlywiO/hBAPf23l4Td5DY2al924jJZdNQfgenUxFK0pFDeZ4uurN2bJkB6LDkUAnBIH5RLfCPZaT1sx3eCkdkjVpSFwT2b4Z5QAXG+MD0FgEUTU6GcUAyiwwszVs4y4+MdFtdg+1SHiqP7906xdKGGCItygo/oEfTeW49lA0gU9WiQZLq5JKairzGdqA31Vp7BQ6TGqj4o4mzJWZBm1YQBkhQ7FrgtndQ9HcCws+GG9GGfJvS95q2VwPWCn+RMtMpuh/KkMpnQiXG7Yon0aGBJfye6h0Olj8IPCF90SZbLCti5cWYPYVOweeCpJZgKkugroDHjhCfVK0kPyezAgMsUaeAU3MuyWKIxfbrQOBxJ1ZM9K04WRLN7rDR9S8v4HqX/K/IxZcqqkxf505DXfAZzRT1xWHUJbo701kz69EZi72JRL6v8zYjZEZgnNofpdwTVVr94qM6t1NrBOFbOMj1RlkOx/qENRtFJWn6LO2t0KR3h+pNrBFO+hQ4WYB6vJ6vsib2OHUGonxNCDQWBw/ZIbWBaUIN/BAFZ5ewcb2tey0ZhNvMnvRLKrMozwrK7QoMXFXiKAy0WcgS02+6M3t9d7i2VPlTguW/kjUN8ugaMmbU1Q9iRv1jPPrENsY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
